### ISSUE TITLE
Doesn't allow me to mark anything

### ISSUE THREAD

**Issue by stevenhorner** [Blendan1/PhotoPrismFaceMarker#1]
I really like the sound of the extension but it doesn't load any way for me to mark anything on the image.

I see the plus button when in the people tab, when I press the button the image loads but clicking doesn't do anything, I actually get stuck on the image. Right clicking only brings up the normal browser context menu and pressing escape doesn't do anything. The only way to get out of the loaded image is to click in the URL bar and reload the page.

Initially tried in Brave browser but then tested in Edge which are both Chrome based. I then installed Chrome just to test and the same results in all 3 browsers.

The extension must be loaded and doing something because it added the plus button.

Happy to do further testing to help resolve the issue.

**Comment by Blendan1** [comment]
I haven't been able to recreate the issue, but maybe you could help me find out what's wrong, there's some info I need from you:

- what version are you using?
- if not the newest please try that one
- is there any error in the console?
- what version of PhotoPrism are you using (probably not the issue but just in case)

**Comment by stevenhorner** [comment]
Just tried on another computer and it works perfectly, strange.

Exactly the same version of PhotoPrism Face Marker v1.0.0

There was no error in the console relating to your extension, the only error in the console relates to PhotoPrism itself but is present whether your extension is installed or not and on both the working computer and the one that doesn't work:
`Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22`

PhotoPrism CE Build 230923-e59851350

I will try again tonight with the laptop that didn't work and see if I have same problem. 

Thank you for writing this extension, this was the biggest missing feature for me from PhotoPrism.

**Comment by Blendan1** [comment]
I might have found the issue, I will make another release tonight, that one will also contain touch and mobile support

As for the issue I'm currently implementing mobile support but deactivated it for the release, but your laptop has a touch input and the browser has enabled its touchapi so it was detected as mobile.


If you can't wait for the release, go in the contentScript and make the isUserUsingMobile function return false

**Comment by stevenhorner** [comment]
That makes sense, it was a Lenovo laptop with a touch screen. I will give the new release a test on the same laptop once it's ready.

Thank you.

**Comment by Blendan1** [comment]
I just made the release, please get back to me if it worked so that I can close the issue

**Comment by stevenhorner** [comment]
Excellent, that works perfectly now on a laptop with a touchscreen as long as you are using the trackpad or a mouse.

Also like that now you can resize, move and delete the box once drawn. Took a little bit of getting used to clicking and dragging as one movement, before it was click once to start, click again to finish the box. This is better with a touchpad or mouse but impossible to do using the touchscreen and presume if a phone browser supports the extension it would also be impossible on a phone. The previous click/touch to start and click/touch to stop would be easier on a mobile I imagine.

**Comment by Blendan1** [comment]
> Excellent, that works perfectly now on a laptop with a touchscreen as long as you are using the trackpad or a mouse.
> 
> Also like that now you can resize, move and delete the box once drawn. Took a little bit of getting used to clicking and dragging as one movement, before it was click once to start, click again to finish the box. This is better with a touchpad or mouse but impossible to do using the touchscreen and presume if a phone browser supports the extension it would also be impossible on a phone. The previous click/touch to start and click/touch to stop would be easier on a mobile I imagine.

The issue with the touch screen is that while your browser provides a touch api it Handels touch input as a mouse input, would it be handled properly the new input is better suited for mobile.

At least that's what I'm thinking, I'm using the extension quite a lot on mobile.

Btw if you're not coming from Reddit I got a way to use the extension in any browser, take a look at simlpejsserver (another one of my projects) for more info or wait until I update the docs
